---
layout: documentation
title: ReactiveX - Catch operator
id: catch
---

<ol class="breadcrumb">
  <li><a href="{{ site.url }}/documentation/operators.html">Operators</a></li>
  <li><a href="{{ site.url }}/documentation/operators.html#error">Error Handling</a></li>
  <li class="active">Catch</li>
</ol>

   <h1>Catch</h1>
   <h3>recover from an onError notification by continuing the sequence without error</h3>
   <figure>
    <img src="images/Catch.png" style="width:100%;" alt="Catch" />
    <figcaption><p>
     The <span class="operator">Catch</span> operator intercepts an <code>onError</code>
     notification from the source Observable and, instead of passing it through to any
     observers, replaces it with some other item or sequence of items, potentially allowing
     the resulting Observable to terminate normally or not to terminate at all.
    </p><p>
     There are several variants of the <span class="operator">Catch</span> operator, and a
     variety of names used by different ReactiveX implementations to describe this operation,
     as you can see in the sections below.
    </p><p>
     In some ReactiveX implementations, there is an operator called something like
     &ldquo;OnErrorResumeNext&rdquo; that behaves like a <span class="operator">Catch</span>
     variant: specifically reacting to an <code>onError</code> notification from the source
     Observable. In others, there is an operator with that name that behaves more like a
     <span class="operator">Concat</span> variant: performing the concatenation operation
     regardless of whether the source Observable terminates normally or with an error. This is
     unfortunate and confusing, but something we have to live with.
    </p></figcaption>
   </figure>

   <h4>See Also</h4>
   <ul>
    <li><a href="concat.html"><span class="operator">Concat</span></a></li>
    <li><a href="retry.html"><span class="operator">Retry</span></a></li>
    <li><a href="http://www.introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html#Catch"><cite>Introduction to Rx</cite>: Catch</a></li>
   </ul>

   <h2>Language-Specific Information:</h2>
<div class="panel-group operators-by-language" id="accordion" role="tablist" aria-multiselectable="true">

  {% lang_operator RxClojure catch* %}
     <figure>
      <img src="images/catchX.png" style="width:100%;" alt="catch*" />
      <figcaption><p>
       RxClojure implements this operator as <code>catch*</code>. This operator takes two arguments,
       both of which are functions of your choosing that take the exception raised by
       <code>onError</code> as their single parameters. The first function is a predicate. If it
       returns <code>false</code>, <code>catch*</code> passes the <code>onError</code> notification
       unchanged to its observers. If it returns <code>true</code>, however, <code>catch*</code>
       swallows the error, calls the second function (which returns an Observable), and passes along
       the emissions and notifications from this new Observable to its observers.
      </p><p>
       You may replace the first function parameter (the predicate that evaluates the exception)
       with a class object representing a variety of exception. If you do this, <code>catch*</code>
       will treat it as equivalent to predicate that performs an <code>instance?</code> check to see
       if the exception from the <code>onError</code> notification is an instance of the class
       object. In other words:
      </p>
      <h4>Sample Code</h4>
      <div class="code clojure"><pre>
(->> my-observable
  (catch* IllegalArgumentException
          (fn [e] (rx/return 1)))
)</pre></div>
      <p>
       is equivalent to:
      </p>
      <div class="code clojure"><pre>
(->> my-observable
  (catch* (fn [e] (-> instance? IllegalArgumentException e))
          (fn [e] (rx/return 1)))
)</pre></div></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxCpp %}
     <p>
      RxCpp does not implement the <span class="operator">Catch</span> operator.
     </p>
  {% endlang_operator %}

  {% lang_operator RxGroovy onErrorResumeNext onErrorReturn onExceptionResumeNext %}
     <p>
      RxGroovy implements the <span class="operator">Catch</span> operator in the same way as
      does RxJava. There are three distinct operators that provide this functionality:
     </p>
     <dl>
      <dt><code>onErrorReturn</code></dt>
       <dd>instructs an Observable to emit a particular item when it encounters an error, and then terminate normally</dd>
      <dt><code>onErrorResumeNext</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error</dd>
      <dt><code>onExceptionResumeNext</code></dt>
       <dd>instructs an Observable to continue emitting items after it encounters an exception (but not another variety of throwable)</dd>
     </dl>
     <h4><code>onErrorReturn</code></h4>
     <figure>
      <img src="images/onErrorReturn.png" style="width:100%;" alt="onErrorReturn" />
      <figcaption><p>
       The <code>onErrorReturn</code> method returns an Observable that mirrors the behavior of the
       source Observable, unless that Observable invokes <code>onError</code> in which case, rather
       than propagating that error to the observer, <code>onErrorReturn</code> will instead emit a
       specified item and invoke the observer&#8217;s <code>onCompleted</code> method, as shown in
       the following sample code:
      </p>
      <h4>Sample Code</h4>
      <div class="code groovy"><pre>
def myObservable = Observable.create({ aSubscriber ->
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('Four');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('Three');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('Two');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('One');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onError();
});

myObservable.onErrorReturn({ return('Blastoff!'); }).subscribe(
  { println(it); },                          // onNext
  { println("Error: " + it.getMessage()); }, // onError
  { println("Sequence complete"); }          // onCompleted
);</pre></div>
      <div class="output"><pre>
Four
Three
Two
One
Blastoff!
Sequence complete</pre></div>
      <ul>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorReturn(rx.functions.Func1)"><code>onErrorReturn(Func1)</code></a></li>
      </ul></figcaption>
     </figure>
     <h4><code>onErrorResumeNext</code></h4>
     <figure>
      <img src="images/onErrorResumeNext.png" style="width:100%;" alt="onErrorResumeNext" />
      <figcaption><p>
       The <code>onErrorResumeNext</code> method returns an Observable that mirrors the behavior of
       the source Observable, unless that Observable invokes <code>onError</code> in which case,
       rather than propagating that error to the observer, <code>onErrorResumeNext</code> will
       instead begin mirroring a second, backup Observable, as shown in the following sample code:
      </p>
      <h4>Sample Code</h4>
      <div class="code groovy"><pre>
def myObservable = Observable.create({ aSubscriber ->
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('Three');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('Two');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('One');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onError();
});
def myFallback = Observable.create({ aSubscriber ->
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('0');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('1');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onNext('2');
  if(false == aSubscriber.isUnsubscribed()) aSubscriber.onCompleted();
});

myObservable.onErrorResumeNext(myFallback).subscribe(
  { println(it); },                          // onNext
  { println("Error: " + it.getMessage()); }, // onError
  { println("Sequence complete"); }          // onCompleted
);</pre></div>
      <div class="output"><pre>
Three
Two
One
0
1
2
Sequence complete</pre></div>
      <ul>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.functions.Func1)"><code>onErrorResumeNext(Func1)</code></a></li>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.Observable)"><code>onErrorResumeNext(Observable)</code></a></li>
      </ul></figcaption>
     </figure>
     <h4><code>onExceptionResumeNext</code></h4>
     <figure>
      <img src="images/onExceptionResumeNextViaObservable.png" style="width:100%;" alt="onExceptionResumeNext" />
      <figcaption><p>
       Much like <code>onErrorResumeNext</code> method, this returns an Observable that mirrors the
       behavior of the source Observable, unless that Observable invokes <code>onError</code> in
       which case, if the Throwable passed to <code>onError</code> is an Exception, rather than
       propagating that Exception to the observer, <code>onExceptionResumeNext</code> will instead
       begin mirroring a second, backup Observable. If the Throwable is not an Exception, the
       Observable returned by <code>onExceptionResumeNext</code> will propagate it to its
       observer&#8217;s <code>onError</code> method and will not invoke its backup Observable.
      </p>
      <ul>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onExceptionResumeNext(rx.Observable)"><code>onExceptionResumeNext(Observable)</code></a></li>
      </ul></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxJava onErrorResumeNext onErrorReturn onExceptionResumeNext %}
     <p>
      RxJava implements the <span class="operator">Catch</span> operator with three distinct
      operators:
     </p>
     <dl>
      <dt><code>onErrorReturn</code></dt>
       <dd>instructs an Observable to emit a particular item when it encounters an error, and then terminate normally</dd>
      <dt><code>onErrorResumeNext</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error</dd>
      <dt><code>onExceptionResumeNext</code></dt>
       <dd>instructs an Observable to continue emitting items after it encounters an exception (but not another variety of throwable)</dd>
     </dl>
     <h4><code>onErrorReturn</code></h4>
     <figure>
      <img src="images/onErrorReturn.png" style="width:100%;" alt="onErrorReturn" />
      <figcaption><p>
       The <code>onErrorReturn</code> method returns an Observable that mirrors the behavior of the
       source Observable, unless that Observable invokes <code>onError</code> in which case, rather
       than propagating that error to the observer, <code>onErrorReturn</code> will instead emit a
       specified item and invoke the observer&#8217;s <code>onCompleted</code> method.
      </p>
      <ul>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorReturn(rx.functions.Func1)"><code>onErrorReturn(Func1)</code></a></li>
      </ul></figcaption>
     </figure>
     <h4><code>onErrorResumeNext</code></h4>
     <figure>
      <img src="images/onErrorResumeNext.png" style="width:100%;" alt="onErrorResumeNext" />
      <figcaption><p>
       The <code>onErrorResumeNext</code> method returns an Observable that mirrors the behavior of
       the source Observable, unless that Observable invokes <code>onError</code> in which case,
       rather than propagating that error to the observer, <code>onErrorResumeNext</code> will
       instead begin mirroring a second, backup Observable.
      </p>
      <ul>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.functions.Func1)"><code>onErrorResumeNext(Func1)</code></a></li>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.Observable)"><code>onErrorResumeNext(Observable)</code></a></li>
      </ul></figcaption>
     </figure>
     <h4><code>onExceptionResumeNext</code></h4>
     <figure>
      <img src="images/onExceptionResumeNextViaObservable.png" style="width:100%;" alt="onExceptionResumeNext" />
      <figcaption><p>
       Much like <code>onErrorResumeNext</code> method, this returns an Observable that mirrors the
       behavior of the source Observable, unless that Observable invokes <code>onError</code> in
       which case, if the Throwable passed to <code>onError</code> is an Exception, rather than
       propagating that Exception to the observer, <code>onExceptionResumeNext</code> will instead
       begin mirroring a second, backup Observable. If the Throwable is not an Exception, the
       Observable returned by <code>onExceptionResumeNext</code> will propagate it to its
       observer&#8217;s <code>onError</code> method and will not invoke its backup Observable.
      </p>
      <ul>
       <li>Javadoc: <a href="http://reactivex.io/RxJava/javadoc/rx/Observable.html#onExceptionResumeNext(rx.Observable)"><code>onExceptionResumeNext(Observable)</code></a></li>
      </ul></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxJS catch onErrorResumeNext %}
     <p>
      RxJS implements the <span class="operator">Catch</span> operator with two distinct
      operators:
     </p>
     <dl>
      <dt><code>catch</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error</dd>
      <dt><code>onErrorResumeNext</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error or if the source Observable terminates normally</dd>
     </dl>
     <h4><code>catch</code></h4>
     <figure>
      <img src="images/catch.js.png" style="width:100%;" alt="catch" />
      <figcaption><p>
       <code>catch</code> is found in the following distributions:
      </p>
      <ul>
       <li><code>rx.js</code></li>
       <li><code>rx.all.js</code></li>
       <li><code>rx.all.compat.js</code></li>
       <li><code>rx.compat.js</code></li>
       <li><code>rx.lite.js</code></li>
       <li><code>rx.lite.compat.js</code></li>
      </ul>
      </figcaption>
     </figure>
     <h4><code>onErrorResumeNext</code></h4>
     <figure>
      <img src="images/onErrorResumeNext.js.png" style="width:100%;" alt="onErrorResumeNext" />
      <figcaption><p>
       This implementation borrows the confusing nomenclature from Rx.NET, in which
       <code>onErrorResumeNext</code> switches to a back-up Observable both on an error <em>and</em>
       on a normal, error-free termination of the source Observable.
      </p>
      <p>
       <code>onErrorResumeNext</code> is found in the following distributions:
      </p>
      <ul>
       <li><code>rx.js</code></li>
       <li><code>rx.compat.js</code></li>
      </ul>
      </figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxKotlin onErrorResumeNext onErrorReturn onExceptionResumeNext %}
     <p>
      RxKotlin implements the <span class="operator">Catch</span> operator in the same way as
      does RxJava. There are three distinct operators that provide this functionality:
     </p>
     <dl>
      <dt><code>onErrorReturn</code></dt>
       <dd>instructs an Observable to emit a particular item when it encounters an error, and then terminate normally</dd>
      <dt><code>onErrorResumeNext</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error</dd>
      <dt><code>onExceptionResumeNext</code></dt>
       <dd>instructs an Observable to continue emitting items after it encounters an exception (but not another variety of throwable)</dd>
     </dl>
     <h4><code>onErrorReturn</code></h4>
     <figure>
      <img src="images/onErrorReturn.png" style="width:100%;" alt="onErrorReturn" />
      <figcaption><p>
       The <code>onErrorReturn</code> method returns an Observable that mirrors the behavior of the
       source Observable, unless that Observable invokes <code>onError</code> in which case, rather
       than propagating that error to the observer, <code>onErrorReturn</code> will instead emit a
       specified item and invoke the observer&#8217;s <code>onCompleted</code> method.
      </p></figcaption>
     </figure>
     <h4><code>onErrorResumeNext</code></h4>
     <figure>
      <img src="images/onErrorResumeNext.png" style="width:100%;" alt="onErrorResumeNext" />
      <figcaption><p>
       The <code>onErrorResumeNext</code> method returns an Observable that mirrors the behavior of
       the source Observable, unless that Observable invokes <code>onError</code> in which case,
       rather than propagating that error to the observer, <code>onErrorResumeNext</code> will
       instead begin mirroring a second, backup Observable.
      </p></figcaption>
     </figure>
     <h4><code>onExceptionResumeNext</code></h4>
     <figure>
      <img src="images/onExceptionResumeNextViaObservable.png" style="width:100%;" alt="onExceptionResumeNext" />
      <figcaption><p>
       Much like <code>onErrorResumeNext</code> method, this returns an Observable that mirrors the
       behavior of the source Observable, unless that Observable invokes <code>onError</code> in
       which case, if the Throwable passed to <code>onError</code> is an Exception, rather than
       propagating that Exception to the observer, <code>onExceptionResumeNext</code> will instead
       begin mirroring a second, backup Observable. If the Throwable is not an Exception, the
       Observable returned by <code>onExceptionResumeNext</code> will propagate it to its
       observer&#8217;s <code>onError</code> method and will not invoke its backup Observable.
      </p></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator Rx.NET Catch OnErrorResumeNext %}
     <p>
      Rx.NET implements the <span class="operator">Catch</span> operator with two distinct
      operators:
     </p>
     <dl>
      <dt><code>Catch</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error</dd>
      <dt><code>OnErrorResumeNext</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error or if the source Observable terminates normally</dd>
     </dl>
     <h4><code>Catch</code></h4>
     <figure>
      <img src="images/Catch.png" style="width:100%;" alt="Catch" />
      <figcaption><p>
       The <code>Catch</code> operator has a variant that allows you to specify which sort of
       Exception you want to catch. If you use that variant of the operator, any other Exceptions
       will be passed through to the observer as if the <code>Catch</code> operator had not been
       applied.
      </p></figcaption>
     </figure>
     <h4><code>OnErrorResumeNext</code></h4>
     <figure>
      <img src="images/OnErrorResumeNext.net.png" style="width:100%;" alt="OnErrorResumeNext" />
      <figcaption><p>
       This implementation introduces a confusing nomenclature, in which in spite of its name
       <code>OnErrorResumeNext</code> switches to a back-up Observable both on an error <em>and</em>
       on a normal, error-free termination of the source Observable. It is therefore more like a
       concatenation operator.
      </p></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxPHP catchError %}
<figure class="variant">
    <figcaption>
    <p>
    RxPHP implements this operator as <code>catchError</code>.
    </p>
    <p>
    Continues an observable sequence that is terminated by an exception with the next observable sequence.
    </p>
<h4>Sample Code</h4>
<div class="code php">
    <pre>
//from https://github.com/ReactiveX/RxPHP/blob/master/demo/catch/catchError.php

$obs2 = Rx\Observable::just(42);

$source = \Rx\Observable::error(new Exception("Some error"))
    ->catchError(function (Exception $e, \Rx\Observable $sourceObs) use ($obs2) {
        return $obs2;
    });

$subscription = $source->subscribe($stdoutObserver);
   </pre>
</div>
<div class="output">
    <pre>
Next value: 42
Complete!
    </pre>
</div>
    </figcaption>
</figure>
  {% endlang_operator %}

  {% lang_operator RxPY catch_exception on_error_resume_next %}
     <p>
      RxPY implements the <span class="operator">Catch</span> operator with two distinct
      operators:
     </p>
     <dl>
      <dt><code>catch_exception</code></dt>
       <dd>instructs an Observable, if it encounters an error, to begin emitting items from a set of other Observables, one Observable at a time, until one of those Observables terminates successfully</dd>
      <dt><code>on_error_resume_next</code></dt>
       <dd>instructs an Observable to concatenate items emitted by a set of other Observables, one Observable at a time, regardless of whether the source Observable or any subsequent Observable terminates with an error</dd>
     </dl>
     <h4><code>catch_exception</code></h4>
     <figure>
      <img src="images/catch_exception.png" style="width:100%;" alt="catch_exception" />
      <figcaption><p>
       You may pass <code>catch_exception</code> a set of back-up Observables either as individual
       function parameters or as a single array of Observables. If it encounters an
       <code>onError</code> notification from the source Observable, it will subscribe to and begin
       mirroring the first of these back-up Observables. If this back-up Observable itself
       issues an <code>onError</code> notification, <code>catch_exception</code> will swallow it
       and switch over to the next back-up Observable. If any of these Observables issues an
       <code>onCompleted</code> notification, <code>catch_exception</code> will pass this along
       and will stop.
      </p></figcaption>
     </figure>
     <h4><code>on_error_resume_next</code></h4>
     <figure>
      <img src="images/on_error_resume_next.png" style="width:100%;" alt="on_error_resume_next" />
      <figcaption><p>
       You may pass <code>on_error_resume_next</code> a set of back-up Observables either as
       individual function parameters, as a single array of Observables, or as a factory function
       that generates Observables. When the source Observable terminates, whether normally or with
       an error, <code>on_error_resume_next</code> will subscribe to and begin mirroring the first
       of these back-up Observables, and then will recursively continue this concatenation process
       for each additional Observable until there are no more Observables to mirror, at which time
       it will pass on the <code>onError</code> or <code>onCompleted</code> notification from the
       last of these Observables.
      </p></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator Rx.rb on_error_resume_next rescue_error %}
     <p>
      Rx.rb implements the <span class="operator">Catch</span> operator with two distinct
      operators:
     </p>
     <dl>
      <dt><code>rescue_error</code></dt>
       <dd>instructs an Observable to begin emitting items from another Observable, or from an Observable returned from an action, if it encounters an error</dd>
      <dt><code>on_error_resume_next</code></dt>
       <dd>instructs an Observable to concatenate items emitted by another Observable to the sequence emitted by the source Observable, regardless of whether the source Observable terminates normally or with an error</dd>
     </dl>
     <h4><code>rescue_error</code></h4>
     <figure>
      <img src="images/rescue_error.png" style="width:100%;" alt="rescue_error" />
      <figcaption><p>
       You may pass <code>rescue_error</code> either an Observable or a factory action that
       generates an Observable.
      </p></figcaption>
     </figure>
     <h4><code>on_error_resume_next</code></h4>
     <figure>
      <img src="images/on_error_resume_next.png" style="width:100%;" alt="on_error_resume_next" />
      <figcaption><p>
       In Rx.rb, <code>on_error_resume_next</code> inherits the misleading nomenclature from Rx.NET
       in that it concatenates the second Observable sequence to the source sequence whether that
       source sequence terminates normally or with an error.
      </p></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxScala onErrorFlatMap onErrorResumeNext onErrorReturn onExceptionResumeNext %}
     <p>
      Rx.rb implements the <span class="operator">Catch</span> operator with four distinct
      operators:
     </p>
     <dl>
      <dt><code>onErrorFlatMap</code></dt>
       <dd>replaces all <code>onError</code> notifications from a misbehaving Observable into the emissions from a secondary Observable</dd>
      <dt><code>onErrorResumeNext</code></dt>
       <dd>instructs an Observable to begin emitting a second Observable sequence if it encounters an error</dd>
      <dt><code>onErrorReturn</code></dt>
       <dd>instructs an Observable to emit a particular item when it encounters an error, and then terminate normally</dd>
      <dt><code>onExceptionResumeNext</code></dt>
       <dd>instructs an Observable to continue emitting items after it encounters an exception (but not another variety of throwable)</dd>
     </dl>
     <h4><code>onErrorFlatMap</code></h4>
     <figure>
      <img src="images/onErrorFlatMap.png" style="width:100%;" alt="onErrorFlatMap" />
      <figcaption><p>
       <code>onErrorFlatMap</code> handles a special case: a source Observable that is noncompliant
       with <a href="../contract.html">the Observable contract</a> in such a way that it may interleave
       <code>onError</code> notifications with its emissions without terminating. This operator allows you to
       replace those <code>onError</code> notifications with the emissions of an Observable of your choosing
       without unsubscribing from the source, so that any future items emitted from the source will
       be passed along to observers as though the sequence had not been interrupted with an
       <code>onError</code> notification.
      </p><p>
       Because <code>onErrorFlatMap</code> is designed to work with pathological source Observables
       that do not terminate after issuing an error, it is mostly useful in debugging/testing
       scenarios.
      </p></figcaption>
     </figure>
     <figure>
      <img src="images/onErrorFlatMap.withMerge.png" style="width:100%;" alt="unintuitive onErrorFlatMap and Merge interaction" />
      <figcaption><p>
       Note that you should apply <code>onErrorFlatMap</code> directly to the pathological source
       Observable, and not to that Observable after it has been modified by additional operators,
       as such operators may effectively renormalize the source Observable by unsubscribing from it
       immediately after it issues an error. Above, for example, is an illustration showing how
       <code>onErrorFlatMap</code> will respond to two error-generating Observables that have been
       merged by the <a href="merge.html"><span class="operator">Merge</span></a> operator:
      </p><p>
       Note that <code>onErrorFlatMap</code> will not react to both errors generated by both
       Observables, but only to the single error passed along by <code>merge</code>.
      </p></figcaption>
     </figure>
     <h4><code>onErrorResumeNext</code></h4>
     <figure>
      <img src="images/onErrorResumeNext.png" style="width:100%;" alt="onErrorResumeNext" />
      <figcaption><p>
       The <code>onErrorResumeNext</code> method returns an Observable that mirrors the behavior of
       the source Observable, unless that Observable invokes <code>onError</code> in which case,
       rather than propagating that error to the observer, <code>onErrorResumeNext</code> will
       instead begin mirroring a second, backup Observable.
      </p></figcaption>
     </figure>
     <h4><code>onErrorReturn</code></h4>
     <figure>
      <img src="images/onErrorReturn.png" style="width:100%;" alt="onErrorReturn" />
      <figcaption><p>
       The <code>onErrorReturn</code> method returns an Observable that mirrors the behavior of the
       source Observable, unless that Observable invokes <code>onError</code> in which case, rather
       than propagating that error to the observer, <code>onErrorReturn</code> will instead emit a
       specified item and invoke the observer&#8217;s <code>onCompleted</code> method.
      </p></figcaption>
     </figure>
     <h4><code>onExceptionResumeNext</code></h4>
     <figure>
      <img src="images/onExceptionResumeNextViaObservable.png" style="width:100%;" alt="onExceptionResumeNext" />
      <figcaption><p>
       Much like <code>onErrorResumeNext</code> method, this returns an Observable that mirrors the
       behavior of the source Observable, unless that Observable invokes <code>onError</code> in
       which case, if the Throwable passed to <code>onError</code> is an Exception, rather than
       propagating that Exception to the observer, <code>onExceptionResumeNext</code> will instead
       begin mirroring a second, backup Observable. If the Throwable is not an Exception, the
       Observable returned by <code>onExceptionResumeNext</code> will propagate it to its
       observer&#8217;s <code>onError</code> method and will not invoke its backup Observable.
      </p></figcaption>
     </figure>
  {% endlang_operator %}

  {% lang_operator RxSwift catchError catchErrorJustReturn %}
     <p>
      <span style="color:#ff0000">TBD</span>
     </p>
  {% endlang_operator %}

</div>
